### ISSUE TITLE
Find out better way of identification of errors in Oops messages

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#465]
Like uniq ID for different enums and theirs cases.

**Comment by bonkey** [comment]
@hani-ibrahim I guess it's valid to close it at this moment, because of general rule not show Oops details to the end user?

**Comment by hani-ibrahim** [comment]
@bonkey I prefer to have this. From my point of view it's too important to have

> OOps
> Something went wrong. Please Try again later #912 

Than 

> OOps
> Something went wrong. Please Try again later

because with the first case if a customer didn't know what is the problem and he always get this error, then he could simply call the customer service and the customer service could ask him about that error number and then look for this number in our internal lockup and find that #912 is for example mapped to Fraud triggered. Then the customer service could help him accordingly.

The ID here will not be meaningful to the user at all, so we are not exposing anything to the user. even 404 error could be mapped to 959 for example.

This could also be useful when talking with other partner that are complaining that too many users are getting generic error and we will not be able to know the exact error without this ID or trying to reproduce the error (which will not always work)

**Comment by bonkey** [comment]
I doubt if you will ever get what user got on a screen.

We should rather have good internal errors tracking through something like #564

**Comment by hani-ibrahim** [comment]
yes, but why I mainly thought about this is the 2 scenarios I mentioned above and they are not handled by Sentry or any other tracking system (easily).

If a user or a partner come to us and said:
> that I got yesterday "OOps. Something went wrong."  why?

we will not be able to answer him unless we dig deep in thousands of logs to know the reason (which we may eventually need to do) but having an error id will shorten the path for us and give us an overview of what was the problem quickly, then we may need to to use Sentry to debug the problem more. But I believe most problem could be solved with just showing the number.

**Comment by bonkey** [comment]
Yeah, theoretically. So, let's bet.

If/when we implement it, first time it helps I'm buying you a box of donuts, otherwise – you buy.

**Comment by hani-ibrahim** [comment]
We can close it :sweat_smile:

**Comment by bonkey** [comment]
🐥!

**Comment by bonkey** [comment]
Meaningful messages will get correct naming and types @ #771, so closing
